require('dotenv').config();
const { Octokit } = require("octokit");

// Initialize GitHub client
const octokit = new Octokit({
  appId: process.env.GITHUB_APP_ID,
  privateKey: process.env.GITHUB_PRIVATE_KEY,
});

// Main webhook handler
async function handleWebhook(req, res) {
  // Verify webhook signature
  const signature = req.headers['x-hub-signature-256'];
  const payload = JSON.stringify(req.body);
  const crypto = require('crypto');
  
  const hash = 'sha256=' + crypto
    .createHmac('sha256', process.env.GITHUB_WEBHOOK_SECRET)
    .update(payload)
    .digest('hex');

  if (signature !== hash) {
    return res.status(401).send('Unauthorized');
  }

  const event = req.headers['x-github-event'];
  const { action, issue, repository } = req.body;

  // Only handle issue opened/edited events
  if (event === 'issues' && (action === 'opened' || action === 'edited')) {
    try {
      console.log(`\n📋 New issue event: ${issue.title}`);
      console.log(`   Repository: ${repository.full_name}`);
      console.log(`   Action: ${action}`);

      // Get installation ID for authentication
      const installations = await octokit.rest.apps.listInstallations();
      const installation = installations.data.find(
        inst => inst.account.login === repository.owner.login
      );

      if (!installation) {
        console.log('⚠️  App not installed on this repository');
        return res.status(200).send('App not installed');
      }

      // Create authenticated client for this installation
      const installationOctokit = new Octokit({
        appId: process.env.GITHUB_APP_ID,
        privateKey: process.env.GITHUB_PRIVATE_KEY,
        installationId: installation.id,
      });

      // QA Test Framework - Ready for you to add tests!
      const testResults = await runQATests(issue, repository);

      // Post comment with results
      await installationOctokit.rest.issues.createComment({
        owner: repository.owner.login,
        repo: repository.name,
        issue_number: issue.number,
        body: testResults.report,
      });

      console.log('✅ Report posted to issue');
      return res.status(200).send('OK');

    } catch (error) {
      console.error('❌ Error handling webhook:', error);
      return res.status(500).send('Error processing webhook');
    }
  }

  // Ignore other events
  return res.status(200).send('Event ignored');
}

// QA Testing Logic - This is where you'll add your actual tests
async function runQATests(issue, repository) {
  console.log('\n🧪 Running QA Tests...');

  // PLACEHOLDER - Replace this with your actual tests
  const passed = true;
  const message = `
✅ **QA Test Report**

**Issue:** ${issue.title}
**Repository:** ${repository.name}
**Status:** Framework ready for testing

---

### Test Results:
- ✅ Framework initialized
- ⏳ Actual tests coming soon (you'll add these!)

### Next Steps:
1. Define test scenarios for this app
2. Add test logic to \`runQATests()\` function
3. Tests will automatically run when issues are created

---

*Generated by Encentrals QA Agent*
`;

  return {
    passed,
    report: message,
  };
}

// Export for Vercel
module.exports = async (req, res) => {
  if (req.method === 'POST') {
    return handleWebhook(req, res);
  }
  
  res.status(200).json({ 
    status: 'QA Agent is running',
    message: 'Send POST requests to this endpoint',
  });
};
